### PR TITLE
Attempt at cleaner code highlighting

### PR DESCRIPTION
**Pull request by pbakaus**
I'm not in love with the baby blue rounded corner style for code on our pages anymore. My current attempt removes backgrounds all together, and introduces a 3px border that signals "here is code", imho making the design cleaner.

Before:
image

After:
image

Thoughts?

### CODE REVIEW

**Comment by bpaduch** [comment]
I always liked having a shaded code box because it draws the attention to the code, which most of us devs like to look at first.  It's hard to notice that with a sidebar. IMHO.

**Comment by pbakaus** [comment]
Another option to fix the baby blue problem is to make the shade light grey, and a little more "boxy". That looks better as well, imho. Thoughts?

image

**Comment by pbakaus** [comment]
Final alternative variant, inset border:
image

**Comment by SidVal** [comment]
I like the **first option**: 

> (...) 3px border that signals "here is code", imho making the design cleaner.-

**Comment by bpaduch** [comment]
Nice! I like that.

**Comment by pbakaus** [comment]
Went with the inset border for now, more conventional option and @bpaduch liked it :) Sorry @SidVal!

**Pull request merged**
