### PR TITLE
Add identical hidden-v3 trigger monitoring

### PR DESCRIPTION
**Pull request by zhouyx**
Keep eventCategory same, changed the eventAction name.
@dvoytenko @lannka

### CODE REVIEW

**Comment by zhouyx** [comment]
woops... wrong repro

**Comment by pbakaus** [comment]
huh? isn't this the right repo?

**Comment by zhouyx** [comment]
😄 my fault! it's the right repo.....

**Comment by pbakaus** [comment]
ok cool :)

**Pull request merged**
