### PR TITLE
💬 Update Guides & Tutorial landing pages.

### PR DESCRIPTION
**Pull request by matthiasrohmer**
As per Sebastian's feedback:

>The problem is that this page is  the Guides & Tutorials landing page, but that’s not obvious (the breadcrumb title is too small to be noticed). I’d prefer it to be “Guides & Tutorial” to make it clear where you are in the documentation

I somehow got used to the `&` 😅 WDYT?

Bildschirmfoto 2019-04-12 um 12 19 50

### CODE REVIEW

**Comment by sebastianbenz** [comment]
I'd leave the `&` as it's shorter. 

How about: "AMP Website Guides & Tutorials"?

**Comment by sebastianbenz** [comment]
//cc @CrystalOnScript

**Comment by matthiasrohmer** [comment]
Open for everything, let's wait on Crystal's feedback 🙂

**Comment by CrystalOnScript** [comment]
+1 on "AMP Website Guides & Tutorials" and use of `&`

**Pull request merged**
