### PR TITLE
Added translations for KO

### PR DESCRIPTION
**Pull request by mshetty2**
Adding file for congratulations@ko.md

### CODE REVIEW

**Comment by mshetty2** [comment]
I signed it!

Thanks,
Manju

**Comment by coryphwang** [comment]
@bpaduch – We just got some extra help from mshetty2 and rachnakumar! It looks like they need to sign the CLA, but once that's done, please take a review of their work. Thanks!

**Comment by bpaduch** [comment]
It looks like you are using the wrong email for your PR vs your CLA email, please see these docs for help on resolving this - https://opensource.google.com/docs/cla/#wrong-email

**Comment by mshetty2** [comment]
Username and email added and verified to the Github account. 
Please let me know if this works.

**Comment by bpaduch** [comment]
Per the instructions in https://opensource.google.com/docs/cla/#wrong-email, if you go to `<your pull request>.patch` (https://github.com/ampproject/docs/pull/951.patch), it will show the email address you committed with.  Is that email the same as the one in GitHub?

**Comment by mshetty2** [comment]
Hi Barb,

Thanks for looking into this!

The email address in the patch is different from my Google email which is
linked to the Github account : https://screenshot.googleplex.com/4o0NoTziMX8
<https://www.google.com/url?q=https://screenshot.googleplex.com/4o0NoTziMX8&sa=D&source=hangouts&ust=1525884629630000&usg=AFQjCNGB_vMMCyCjV7r_ZO2XwvULtaEaqA>

However, I chatted with Peter and executed the below commands to set
username and email in git.

git config user.name
git config user.email
Should I resubmit the pull requests to reflect the changes?

Appreciate your insights!

Thanks,
Manju

**Comment by mshetty2** [comment]
I resolved it.

**Pull request closed without merging**
