### PR TITLE
Create file-a-bug@es.md

### PR DESCRIPTION
**Pull request by SidVal**
This is for translate https://www.ampproject.org/es/docs/contribute/
The part of "file a bug"

### CODE REVIEW

**Comment by bpaduch** [comment]
Hi Sid, this isn't needed as you are already translating the title in [messages.po](https://github.com/ampproject/docs/blob/master/translations/es/LC_MESSAGES/messages.po#L382).

The title in this file is a translation variable (indicated by the `@`), so it's pulled into the messages file.

**Comment by bpaduch** [comment]
Hi Sid, this isn't needed as you are already translating the title in [messages.po](https://github.com/ampproject/docs/blob/master/translations/es/LC_MESSAGES/messages.po#L382).

The title in this file is a translation variable (indicated by the `@`), so it's pulled into the messages file.

**Comment by SidVal** [comment]
Ok. But [here](https://github.com/ampproject/docs/blob/master/translations/es/LC_MESSAGES/messages.po#L382) said that it's translated. Why does not show  in spanish?

**Comment by bpaduch** [comment]
Ah, that is a good find.  I'll submit a fix for that so it picks up the translation variable!

**Comment by SidVal** [comment]
Thanks @bpaduch ... one more doubt.
In the same URL, you will see: `Integrate your technology with AMP` and `Open Source Governance`, where is or should be that translations ? (I'm lost :-1:  )

**Comment by bpaduch** [comment]
Hi Sid, 
Those two are the titles for two docs, that aren't translated, and so they appear as English (same as in the left-hand navigation).  Once translated, they will appear in Spanish.

If you have further questions, join the Slack channel and the "docs" thread for further docs discussions. :)

**Comment by SidVal** [comment]
Oh, sure Barb. 
Thank you again !

**Pull request closed without merging**
