### PR TITLE
Fix broken breadcrumbs

### PR DESCRIPTION
**Pull request by derekcecillewis**
Corrects breakage due to variable scope.

### CODE REVIEW

**Comment by derekcecillewis** [comment]
cc @aghassemi

**Comment by pbakaus** [comment]
@jeremydw heads up Jeremy, this is a PR that workd around a super odd issue that I consider a Grow bug: This file creates breadcrumbs for pages (e.g. [on this page](https://www.ampproject.org/case-studies/washingtonpost/), right under the header). In its current version (before this PR, current master), it successfully creates the breadcrumbs during development (`grow run`), but *not* during build.

It's very likely that we did something wrong – yet, I'd argue there should be any differences in how `grow run` and `grow build` render pages. Thoughts?

**Comment by derekcecillewis** [comment]
@pbakaus When I cloned the latest version of this repo yesterday afternoon, the breadcrumbs weren't working during development (`grow run`) either. It's odd that you didn't have this experience as well. I had been using that same implementation of breadcrumbs in production on another one of my sites for several months and had no issues. I'd be curious to know what changed.

**Comment by derekcecillewis** [comment]
Alright, I had a few spare moments and decided to investigate further. It appears to be a very common breakage as can bee seen in [an issue](https://github.com/pallets/jinja/issues/641) about this in the Jinja repo. The most probable reason (correct me if I'm wrong) why you were experiencing inconsistencies between `grow run` and `grow build` is because the production deployment is built using the latest version of Grow (0.1.2), while your local version of Grow is still at 0.0.68. In v0.0.68, the Jijna2 dependency was at 2.8, yet the latest release of Grow has Jinja2 updated to v2.9.6. As was reported in the linked issue, the breakage occurs after Jinja2 v2.9. They are working on a cleaner workaround than what I've provided here, but it has yet to be merged.

**Comment by pbakaus** [comment]
Interesting, thanks for the investigation! I'll merge this for now. Thanks much.

**Pull request merged**
