### PR TITLE
Adding NoBroker Case Study

### PR DESCRIPTION
**Pull request by elegeros**
New case study from India-based peer-to-peer apartment rental site.

### CODE REVIEW

**Comment by bpaduch** [comment]
the "nobroker-frame1" file must be renamed to "nobroker_frame1" otherwise the image doesn't display

OR

change your code to use the "nobroker-frame1" file name.

**Comment by elegeros** [comment]
I signed it.

**Comment by elegeros** [comment]
I signed it!

**Comment by elegeros** [comment]
I signed it!

**Pull request merged**
