### PR TITLE
Added Pinpoll to the analytics-vendors page

### PR DESCRIPTION
**Pull request by jfitzinger**
Please add Pinpoll to the vendors page after this PR is completed: [amphtml/pull/19578](https://github.com/ampproject/amphtml/pull/19578)

### CODE REVIEW

**Comment by jfitzinger** [comment]
Could you please review this change?
https://github.com/ampproject/docs/pull/1314 was approved. CLA is now signed.
Thank you!

**Comment by pbakaus** [comment]
Thank you, apologies for the delay!

**Comment by jfitzinger** [comment]
@pbakaus I was just alerted to the fact, that Pinpoll is no longer listed on the [AMP analytics vendor page](https://amp.dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors?referrer=ampproject.org#pinpoll). 
Could you please help us getting this fixed?

**Comment by torch2424** [comment]
cc @pbakaus and possibly maybe @CrystalOnScript or @sebastianbenz .

Can you help out @jfitzinger ? Thanks! 😄

**Comment by pbakaus** [comment]
@matthiasrohmer can you take a look whether this was accidentally removed during the migration to amp.dev? Thanks!

**Comment by matthiasrohmer** [comment]
Indeed this got lost, readded it with e26eb30.

**Pull request merged**
