### PR TITLE
✨add video for stamp ad template

### PR DESCRIPTION
**Pull request by calebcordry**
Hosting the video here so that we can use it in example ads. We will be serving it into the example story here https://amp.dev/documentation/examples/advertising-analytics/doubleclick_amp_story_ads/

The rest of the changes will be made in Google ad manager, but they do not host videos.

### CODE REVIEW

**Comment by calebcordry** [comment]
cc/ @jasti

**Comment by calebcordry** [comment]
Thanks for the quick response. Is this better?

**Comment by sebastianbenz** [comment]
Almost, can you make it: `amp-stories-ad-template-single-video` (STAMP is only our internal name).

**Comment by calebcordry** [comment]
Done.

**Comment by sebastianbenz** [comment]
Thanks a lot!

**Comment by sebastianbenz** [comment]
When do you need this to be live?

**Comment by calebcordry** [comment]
Not a huge rush, when is your next planned release?

**Pull request merged**
