### PR TITLE
Adds readme for animations and comments

### PR DESCRIPTION
**Pull request by kul3r4**
- add readme.txt to the templates using animations (text, single image, multiple image)
- add additional comments how to view templates when animations are in place
- fix path of an image for single image template

@calebcordry PTAL

### CODE REVIEW

**Comment by kul3r4** [comment]
@ithinkihaveacat FYI

**Comment by calebcordry** [comment]
Thanks! I cant actually see anything inside the files

**Comment by kul3r4** [comment]
Which files in particular? Do you mean they are empty?

**Comment by calebcordry** [comment]
Sorry, I just meant that the github diff view doesn't show what is inside the files. I then realized that I could just download the PE :). Anyway LGTM, thanks again!

**Comment by kul3r4** [comment]
@sebastianbenz PTAL

**Pull request merged**
