### PR TITLE
Allow samples to override title via metadata

### PR DESCRIPTION
**Pull request by fstanis**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Which problem does this solve?

**Comment by matthiasrohmer** [comment]
@sebastianbenz, would allow email samples having titles without an actual `<title>` element. Also see #2059.

**Comment by sebastianbenz** [comment]
This doesn't solve the problem. See me comment in the issue.

**Comment by fstanis** [comment]
Ugh, you're right, I just realized this won't affect the playground...

**Pull request closed without merging**
