### PR TITLE
French Translation (In-progress)

### PR DESCRIPTION
**Pull request by wassgha**

### CODE REVIEW

**Comment by bpaduch** [comment]
"In Progress" means do not merge?

**Comment by wassgha** [comment]
Hey @bpaduch ! I am not sure how this repository is managed so I'm not sure if it's ok to merge partial translations or not. I mainly work on the amphtml repo and I did this on my spare time. Hopefully I aim to translate a few more bits every now and then so it depends on whether you accept partial translations or you want to wait till everything is translated to merge :)

**Comment by bpaduch** [comment]
I can merge any little bits of translation but it might make better sense for you to keep the file locally  until you are completed the translations for that particular file - for example, do all strings in messages.po for the specified language.  

If I see "Work In Progress" then I think - oh, this PR isn't complete and waiting on something.  Please submit PRs that are ready to go into production.

**Comment by wassgha** [comment]
Awesome thanks!

**Pull request merged**
