### PR TITLE
Add amp-instagram js snippet to example code.

### PR DESCRIPTION
**Pull request by mikelax**

### CODE REVIEW

**Comment by mikelax** [comment]
I signed it!

**Comment by pbakaus** [comment]
Is this still relevant? It looks like it's already in there? Let me know (and resolve conflicts).

**Comment by mikelax** [comment]
@pbakaus this PR can be closed. [This recent commit](https://github.com/ampproject/docs/commit/409032353cb6a6a6441abe2cf71434784f35d2cd) made the same change.

**Comment by pbakaus** [comment]
@mikelax thanks for letting me know!

**Pull request closed without merging**
