### PR TITLE
List translations as rel="alternate"

### PR DESCRIPTION
**Pull request by rowan-m**
An additional but only **potential** fix for #331 

Currently all translations are listed as `canonical` URLs. This change makes "`en`" the canonical and all translations are listed as "`alternate`". I believe this is inline with the advice given here: https://support.google.com/webmasters/answer/189077

However, given that all the translations are currently live as canonical at the moment and **indexed** I'm not sure if there's anything that needs to be considered before merging this.

### CODE REVIEW

**Comment by rowan-m** [comment]
As a _tl;dr,_ it means that the current output:

```html
  <link rel="canonical" href="https://www.ampproject.org/es/docs/reference/components/amp-bind.html">
```

Would become:

```html
  <link rel="alternate" hreflang="ar" href="https://www.ampproject.org/ar/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="de" href="https://www.ampproject.org/de/docs/reference/components/amp-bind.html" />
  <link rel="canonical" hreflang="en" href="https://www.ampproject.org/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="es" href="https://www.ampproject.org/es/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="fr" href="https://www.ampproject.org/fr/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="id" href="https://www.ampproject.org/id/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="it" href="https://www.ampproject.org/it/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="ja" href="https://www.ampproject.org/ja/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="ko" href="https://www.ampproject.org/ko/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="pl" href="https://www.ampproject.org/pl/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="pt_BR" href="https://www.ampproject.org/pt_br/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="ru" href="https://www.ampproject.org/ru/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="th" href="https://www.ampproject.org/th/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="tr" href="https://www.ampproject.org/tr/docs/reference/components/amp-bind.html" />
  <link rel="alternate" hreflang="zh_CN" href="https://www.ampproject.org/zh_cn/docs/reference/components/amp-bind.html" />
```

**Comment by rowan-m** [comment]
@pbakaus updated the branch and it looks clean.

**Comment by rowan-m** [comment]
Oh, sorry - ignore that, will sort out the rebase too.

**Comment by pbakaus** [comment]
any progress?

**Comment by pbakaus** [comment]
@rowan-m ping!

**Comment by bpaduch** [comment]
@rowan-m: Ping.

**Comment by bpaduch** [comment]
@rowan-m - Continue working on this or close this?

**Pull request closed without merging**
