### PR TITLE
Fix/sidebar

### PR DESCRIPTION
**Pull request by sebil**
With this PR the sidebar becomes much more usable again.
Both, the format-toggle and the sidebar-toggle stay sticky at the same height.
If you scroll inside the sidebar the format-toggle stays at its position.
Autoscrolling to an active nav-item is still working with this modification.
Also there are some bug-fixes and code and styling improvements.

Relies to #2194 and #2195

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
@sebastianbenz you want to have look before merge?

**Comment by sebil** [comment]
Thanks for the feedback.
I'm going to tweak this a little now.

In the meantime, can you tell me if you still want the component-sidebar letters to be collapsable when inactive?
I thought about this, and I'm not sure if it really improves the usability of the sidebar.

Here is a test screenshot how it would look like (arrows missing).
component-sidebar-test

**Comment by sebastianbenz** [comment]
You're right. Doesn't work too well. Thanks for flagging this. How about
showing letters as shortcuts on the right-hand side? Similar to the iOS
contacts app: find-fix-missing-contacts-ios-7-1-2.w1456.jpg
<https://img.gadgethacks.com/img/35/14/63541628772516/0/find-fix-missing-contacts-ios-7-1-2.w1456.jpg>
.

>

**Comment by matthiasrohmer** [comment]
@sebastianbenz, would you be fine approving this and let @sebil deal with improving the animation tomorrow? I know the sidebar has been ugly for a while but that's our chance to have it broken one day less 😉

**Comment by sebil** [comment]
> You're right. Doesn't work too well. Thanks for flagging this. How about showing letters as shortcuts on the right-hand side? Similar to the iOS contacts app: find-fix-missing-contacts-ios-7-1-2.w1456.jpg <https://img.gadgethacks.com/img/35/14/63541628772516/0/find-fix-missing-contacts-ios-7-1-2.w1456.jpg> .
> […](#)

I opened a new issue to keep this alive #2269

**Pull request merged**
