### PR TITLE
Remove hamburger menu random gray box

### PR DESCRIPTION
**Pull request by morsssss**
Remove box-shadow so that mysterious gray box won't appear on hamburger menu hover.

I don't believe this rule applies anywhere else on the site.  I did look around!

Fixes: https://github.com/ampproject/docs/issues/472

### CODE REVIEW

**Comment by bpaduch** [comment]
@morsssss - I tested this and it turns out that box-shadow is used for tabs, which are used in desktop.  By removing it, tabs are not easily distinguishable: 

drop-shadow

**Comment by morsssss** [comment]
I'm glad you tested and found that!  I'm sure I can scope the rule less broadly. Will take a look.

**Comment by morsssss** [comment]
Think I did it the right way this time.  Please review!

**Comment by bpaduch** [comment]
Nice!

**Pull request merged**
