### PR TITLE
Enhance 404 page styling with simple amp-bind game.

### PR DESCRIPTION
**Pull request by garanj**
As discussed @bpaduch some styling enhancements to the 404 page following pull request #758. Lighthearted demonstration of amp-bind.

### CODE REVIEW

**Comment by bpaduch** [comment]
It looks good and functions.  I'm wondering if you might want to have some leading text so the user wonders what it is, and what the reset button is (they might think the button is related to fixing the 404).  Perhaps something like "While you're here, play a game of tic-tac-toe made with AMP".  Or "Try your luck with a game of ...".  

@pbakaus - can you review too.

Preview available here: https://barb-ampdocs.firebaseapp.com/docX

**Comment by garanj** [comment]
Reset button could be renamed to "Restart game" ?
"While you're here, play a game of tic-tac-toe made with AMP" - sounds good, reinforces it was made with AMP too.

**Comment by garanj** [comment]
I think it reads better now!

**Comment by bpaduch** [comment]
@pbakaus - Can you also review.  Just wanted your eyes on it too.

**Comment by morsssss** [comment]
Just wanted to say I'm excited that this game has found an excellent home 😊

**Pull request merged**
