### PR TITLE
Fix links to localized pages

### LINKED ISSUE #352: Links within translated docs don't link to the localized language's page
On a localized page, links to an anchor on the same page or a link to a different page on the site goes to the English page, not the localized page for the selected language.

Examples: 

On the [French page for "Supported CSS"](https://www.ampproject.org/fr/docs/guides/author-develop/responsive/style_pages), the link for [**polices personnalisées**](https://www.ampproject.org/fr/docs/guides/author-develop/responsive/style_pages#the-custom-fonts-exception) doesn't go anywhere because  the anchor is wrong (`#add-styles-to-a-page` should be `#exception-les-polices-personnalisees`).  

On the [French page for "Styling & Layout"](https://www.ampproject.org/fr/docs/guides/author-develop/responsive_amp), the link for [**mises en page compatibles avec les pages AMP**](https://www.ampproject.org/docs/guides/responsive/control_layout.html) takes you to the English page but it should take you to the [French page](https://www.ampproject.org/fr/docs/guides/author-develop/responsive/control_layout).

Fixes involve a couple things:
1) Links to other pages on ampproject should go to the same language selected. For example, /docs/guides/debug/validate.html should be **/fr**/docs/guides/debug/validate.html.
2) If it's an anchor link, ensure the anchor name is localized. For example, `#add-styles-to-a-page` should be `#exception-les-polices-personnalisees`.

This affects all localized pages.

Related: https://github.com/ampproject/docs/pull/348

### PR DESCRIPTION
**Pull request by bpaduch**
Correct links to localized pages, including lang code and any anchors. Tested locally. (part 2 of 2)

Fixes #352

### CODE REVIEW

**Comment by pbakaus** [comment]
@jeremydw there must be a smarter way to link to one localized page from another localized page in Grow. Jeremy, can you give insight?

**Comment by jeremydw** [comment]
I don't have any great tips for what to do in Markdown, but here's how you'd do this in a Jinja template:

```
{# Link to /content/pages/page.yaml - same locale as current page. #}
{{g.doc('/content/pages/page.yaml', locale=doc.locale).url.path}}

{# Link to DE verison of the current page. #}
{{doc.localize('de').url.path}}
```

You can, of course, use Jinja syntax within Markdown if you pipe the Markdown result to `|render`. For example:

```
{# Treats the HTML output from Markdown as Jinja and renders it.
{{doc.html|render}}
```

Let me know if you have any syntax suggestions and we can build them into Grow.

**Comment by jeremydw** [comment]
Also instead of hardcoding the current locale, e.g. `ko` in a link, if you're piping the result to Jinja render, you can of course use `{{doc.locale}}`.

**Comment by bpaduch** [comment]
Let's merge this for now; and I'll investigate this syntax suggestion.

**Comment by pbakaus** [comment]
OK SGTM. Thanks @jeremydw for the insights!

**Pull request merged**
