### PR TITLE
added mediaimpact.md and arranged the list alphabetically

### PR DESCRIPTION
**Pull request by adtechnology**

### CODE REVIEW

**Comment by adtechnology** [comment]
I signed it!

**Comment by pbakaus** [comment]
You will need to contribute this to the main amphtml repo, since this is
just a mirror that gets pulled in automatically. On the road right now, but
if you can't find it, I'll add a link to show you where.

**Comment by adtechnology** [comment]
Alrigth, a link would be great i couldn't find it till now

**Comment by pbakaus** [comment]
Argh sorry for the delay! Here's the link: https://github.com/ampproject/amphtml/blob/master/builtins/amp-ad.md

**Pull request closed without merging**
