### PR TITLE
Fix heading in prepare_for_discovery.md

### PR DESCRIPTION
**Pull request by mdwelsh**
<link> needs to be backticked here or else it won't render in the final HTML.

### CODE REVIEW

**Comment by mdwelsh** [comment]
I am a Googler and have contributed to Google projects on open source in the past.

**Comment by pbakaus** [comment]
Looks goos, can you resolve the conflict? I'll merge right afterwards.

**Comment by mdwelsh** [comment]
Conflict resolved.

**Comment by pbakaus** [comment]
Thanks!

**Pull request merged**
