### PR TITLE
new header design

### PR DESCRIPTION
**Pull request by robertosobachi**
refactor: new header design
refactor: link on footer to the github repo
feat: new mixin for flex-box
feat: new mixin for vendor prefixes

### CODE REVIEW

**Comment by erwinmombay** [comment]
@Meggin can you review this?

**Comment by Meggin** [comment]
Reviewing now-- just need to set things up a bit.

**Comment by Meggin** [comment]
Hey,

I added comments inline, and one main comment-- can't see content in the
activated hamburger menu. I checked in devtools, and the values are there,
but they just aren't visible.

That's the biggest issue to fix.

**Comment by Meggin** [comment]
I retested and the menu is working and the github icon is removed; however, the logo.svg is black instead of blue on home page. Can we make these consistent? Also, can you sign the cla?

**Comment by Meggin** [comment]
@pbakaus - you might want to test this, as there's quite a bit of CSS changes.

**Comment by robertosobachi** [comment]
I signed a Contributor License Agreement. I signed it as an Individual since it seemed more complicated to get this signed on behalf of the corporation I'm working for: Toaster Ltd.

**Comment by robertosobachi** [comment]
Created a new pull request with a new account with a valid CLA signed.

**Comment by pbakaus** [comment]
Closing this due to the new PR.

**Pull request closed without merging**
