### PR TITLE
Added description for dynatrace

### PR DESCRIPTION
**Pull request by kamtschatka**
Related to Issue #492:
Readded (and updated) the description for dynatrace amp-analytics support.

### CODE REVIEW

**Comment by kamtschatka** [comment]
Not sure, why the bot still complains about me not signing the CLA, I had the same issue before and for the other pull request i made, someone was able to confirm that....

So just in case: 
I signed it!

**Comment by bpaduch** [comment]
@kamtschatka - To confirm, if you look at https://github.com/ampproject/docs/pull/493.patch, the email address in there, is that the one you have in your GitHub account?  The email address on commits, PRs and such must = the email you have in your GitHub account.

**Comment by kamtschatka** [comment]
Yes, the email address is my public and primary email address for this account(there are no other email addresses assigned to this account)

**Comment by bpaduch** [comment]
I'm investigating with CLA.  I'll update the PR when I get info.  Thx.

**Comment by bpaduch** [comment]
Hi Simon, it looks like you might have used a different email address account to manage the Dynatrace LLC contributor group.  Please add your @dynatrace.com email to the Dynatrace LLC contributor group.  This should resolve the CLA issues.

**Comment by bpaduch** [comment]
Thank you!

**Comment by kamtschatka** [comment]
Thanks for the help

**Pull request merged**
