### PR TITLE
Update AMPCS2019 page summary, FAQ and location

### PR DESCRIPTION
**Pull request by mrjoro**
A few quick edits before we launch the application:
- Updating the blurb to match our summary of the summit from the blog post
- Updating the FAQ to remove AMP Conf references & make it clear who the target audience for this summit is
- Updating the location to remove AMP Conf references

/cc @vishaldodiya

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
Could also be added later but you might want to add a banner at the top just as we had for the AMPConf 🙂See `frontend/templates/views/partials/banner.j2`.

**Comment by mrjoro** [comment]
@pbakaus it looks like @matthiasrohmer has the answer for the banner question :)

**Comment by matthiasrohmer** [comment]
... it additionally needs to be enabled in `frontend/templates/views/partials/header.j2`:12 😉

**Comment by pbakaus** [comment]
@matthiasrohmer yes please! Can you help us add one in another PR? Not sure how to bring it back.

**Pull request merged**
