### PR TITLE
Ads & Email Sample Preview.

### PR DESCRIPTION
**Pull request by matthiasrohmer**
This adds the email header to the sample preview for amp4email and gets rid of the lengthy "AMP Example Preview" header but just prefixes the samples title with "Preview:".

I was about to include the beautified ads preview with this but that needs a little more love tomorrow.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Looks good! We also need a desktop version with a width of 800px.

**Comment by matthiasrohmer** [comment]
Sorry it took so long! I was quite unsatisfied with what I did so far and also the current structure made it hard for me to add the ads preview, therefore I'd gave it an overhaul. PTAL now, ads preview is included as well, without the device switcher for it though as samples like Scrollbound Animation Ad ask for a scrollable `body`.

The Lightbox Ad sample seems broken on amp.dev but works on [abe.com](https://ampbyexample.com/amp-ads/experimental_ads/lightbox_ad/preview/). Haven't had a close look, maybe you quickly spot what's wrong.

**Comment by sebastianbenz** [comment]
Few comments:

* Preview: the title, the logo and the back link have different font sizes
* The ads preview should have a scrollable device view. The current version is not scrollable on a large desktop
* story and email preview: the background does not fill the whole page

Screenshot 2019-03-29 at 08 43 23

**Comment by matthiasrohmer** [comment]
Increased the amount of text to scroll and fixed the styling bugs. Additionally I pushed `perf/sample-preview-ads` for you to investigate on the scrolling behaviour, checkout: http://localhost:8080/documentation/examples/introduction/scrollbound_animation_ad/preview/index.html?format=ads - also noticed that switching devices might be pointless as the ads don't resize.

**Comment by sebastianbenz** [comment]
Thanks!

+1 to not switching devices (the preview width needs to scale with the ad width though). 

Regarding scroll bound effects not working. Try embedding the ad preview into an iframe.

One other thing: mobile version is broken at the moment:

Screenshot 2019-04-01 at 09 05 36

**Comment by matthiasrohmer** [comment]
>(the preview width needs to scale with the ad width though).

Not 100% sure what you mean by that: setting an inline `min-width` on the device pane to make sure the ad fits?

>Regarding scroll bound effects not working. Try embedding the ad preview into an iframe.

No luck with `amp-iframe` either 😕 

>One other thing: mobile version is broken at the moment:

Fixed.

**Comment by sebastianbenz** [comment]
> Not 100% sure what you mean by that: setting an inline min-width on the device pane to make sure the ad fits?

The width of the ad is configurable via metadata. If the ad has a width of 400px the preview needs to have the same width.

**Comment by matthiasrohmer** [comment]
Added logic to build the embeds but still need to integrate them in the actual preview view. Will do so tonight, but quickly need to take a break.

**Comment by matthiasrohmer** [comment]
Ads preview should now work as intended - together with my friend Scrollbound Animation Ad.

**Comment by sebastianbenz** [comment]
When I run the PR locally, the ads preview shows the homepage.

**Comment by sebastianbenz** [comment]
The title still overflows for me:

Screenshot 2019-04-03 at 08 44 44

**Comment by sebastianbenz** [comment]
One other thing: can we center the preview on the page?

**Comment by matthiasrohmer** [comment]
Bildschirmfoto 2019-04-03 um 23 24 55

Preview title on mobile now has ellipsis and "Preview:" prefix gets hidden on smaller screens.

I had the device frame centered before that sadly had strange side effects with `transform: scale`. 😕

**Comment by sebastianbenz** [comment]
Let's do device frame centering later then. 

Ellipsis is good. Two additional suggestions:

1. smaller font size
2. remove `AMP`
3. we need a close/back button

**Comment by matthiasrohmer** [comment]
Didn't consider the mobile view as such a strong use case initially as we are hiding the "View demo" on mobile nevertheless 😅  As it's now optimized we can probably unhide it, WDYT?

Bildschirmfoto 2019-04-04 um 00 08 02

**Comment by sebastianbenz** [comment]
I wasn't even aware that we hide it on mobile. Definitely unhide! 

Another thing, you can make the preview take the full width of the screen.

**Comment by matthiasrohmer** [comment]
I was mistaken, just the playground button is hidden. Preview pane now spans the whole viewport.

**Comment by sebastianbenz** [comment]
Can you fix the lint errors.

**Pull request merged**
