### PR TITLE
Add EPICA

### PR DESCRIPTION
**Pull request by aleksei-a-savitski**
Add EPICA to amp-analytics vendors list. See https://github.com/ampproject/amphtml/issues/18808.

### CODE REVIEW

**Comment by CrystalFaith** [comment]
@abiaskosty - thanks for sending up this update! However, I won't be able to merge it until you fix the cla issue :)

**Comment by abiaskosty** [comment]
I signed it!

**Comment by jeffjose** [comment]
@CrystalFaith Friendly ping :)

@torch2424  FYI

**Comment by abiaskosty** [comment]
Hi! Is something pending before this pull reqeust can be merged?

**Comment by torch2424** [comment]
@abiaskosty 

I'll ping @CrystalFaith directly to get this in 😄

**Comment by CrystalFaith** [comment]
Thanks for your patience!

**Pull request merged**
