### PR TITLE
Added Stripo email editor to tools

### LINKED ISSUE #2438: Add "Stripo email editor" to the AMP Tools Listing
## Request to add third-party tool/service/platform/vendor

**1. What's the name?**
Stripo email editor

**2. For which format?**
email

**3. What type is it?**
editor

**4. What page should it appear on?**
2. [amp.dev/documentation/tools](https://amp.dev/documentation/tools)

**5. If you choose 2 in Step 4:**
https://stripo.email/amp-support/
https://stripo.email/blog/how-to-build-amp-emails-with-stripo/
https://stripo.email/blog/how-to-build-amp-carousel-for-your-emails-with-stripo/

### PR DESCRIPTION
**Pull request by antongrinenko**
Fixes #2438.

### CODE REVIEW

**Comment by antongrinenko** [comment]
I signed it!

**Comment by matthiasrohmer** [comment]
@fstanis requested you for review according to ampproject/wg-outreach#15 as you're part of the wg-amp4email.

**Comment by fstanis** [comment]
Approved, but the CLA seems to still be pending. You may have used a different address in your commit, to fix that:

1. Go to https://cla.developers.google.com/clas and check which email you used
2. Make sure this is the one git uses: `git config --global user.email youremail@example.com`
3. Rewrite the email in your last commit: `git commit --amend --reset-author --no-edit`
4. Force push: `git push origin future -f`

**Comment by antongrinenko** [comment]
> Approved, but the CLA seems to still be pending. You may have used a different address in your commit, to fix that:
> 
> 1. Go to https://cla.developers.google.com/clas and check which email you used
> 2. Make sure this is the one git uses: `git config --global user.email youremail@example.com`
> 3. Rewrite the email in your last commit: `git commit --amend --reset-author --no-edit`
> 4. Force push: `git push origin future -f`

Done

**Comment by DKulaksyz** [comment]
Hello @matthiasrohmer , can we ask you to review the cla/google check again? Thanks

**Comment by fstanis** [comment]
The CLA is reviewed automatically, neither Matthias nor I can do much here.

Go to https://cla.developers.google.com/clas and make sure it's signed with the correct username (@antongrinenko need to do it, as the author of the PR) and with the same email used in the commits (the one you set with `git config --global user.email youremail@example.com`). If this email is not listed, add it in https://github.com/settings/profile

**Comment by DKulaksyz** [comment]
Thank you, Fillip. Will check with Anton again.

**Comment by DKulaksyz** [comment]
@fstanis seems like we did it :) Thanks a for the help

**Pull request merged**
