### PR TITLE
Added Retargetly as a new analytics vendor

### PR DESCRIPTION
**Pull request by fdnieves**
Added Retargetly vendor description inside content/docs/analytics/analytics-vendors.md file.

### CODE REVIEW

**Comment by pbakaus** [comment]
Looks good, thanks!

**Comment by fdnieves** [comment]
Hi! One question @pbakaus , this file that I changed is the one that is present on https://www.ampproject.org/docs/analytics/analytics-vendors ?

Also, I may need to change https://www.ampproject.org/support/faqs/supported-platforms page. Do you know if analytics vendors are listed on any other page?

Thanks !

**Comment by pbakaus** [comment]
@fdnieves yes, that's correct. That's the only place needed, it will automatically update the supported platforms page.

**Comment by fdnieves** [comment]
It's there now! Thanks for your answer Paul.

**Pull request merged**
