### PR TITLE
Improve vertical rhythm and normalize typography across all pages

### PR DESCRIPTION
**Pull request by pbakaus**
Hi everyone,

I've wasted a lot of time on this after @cramforce and I discussed typographic issues on amp.dev, but this PR normalizes and fixes a bunch of issues with the typography in our docs (and hopefully other sections).

| Before | After |
| --- | --- |
| amp dev_documentation_guides-and-tutorials_develop_animations_triggering_css_animations html_format=websites | localhost_8080_documentation_guides-and-tutorials_develop_animations_triggering_css_animations html_format=websites |

A couple highlights:

- The sizes of h1-h5 change more proportionally now, headline of the page is bigger than the h2 right after
- There's appropriate margin between elements, and h1-h3 always leaves a little more gap on top
- Lists don't have gaps in-between list items, fixing a lot of long list issues
- Paragraphs have an actual full line margin between them
- The new code font looked bigger than Noto (even though it wasn't) so I reduced its size by a little, normalizing the look.

Some potential issues:

- This is a wide change, but I tested a massive amount of pages.
- The biggest question: This also normalizes the look on many non-doc sub pages, so that we don't have wildly varying h1-h5 sizes everywhere. Some pages will have slightly smaller sub headings for that reason. I'm curious to hear your opinions on this.

Please give it a test run! Would like to merge this, or at least a variant contained to the docs soon in prep for AMP Conf. Thanks.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Much better (just from looking at the screenshots)! I'd be great if we could define the core margins as variables and use these across the site to ensure consistency.  

Sidenote: I'm really not of a fan of how the `&` looks in Poppins.

**Comment by cramforce** [comment]
Woohoo!

**Comment by sebastianbenz** [comment]
I've deployed this PR to staging for easier testing:
https://amp-dev-staging.appspot.com

**Comment by pbakaus** [comment]
@sebastianbenz thanks for staging it! I couldn't test the samples before, so if you see anything fishy there let me know (I checked just now and didn't find any). Please approve as well when done testing and I'll merge.

Re: Poppins, I agree, and this is the third time I heard negative feedback about Poppins. Might need to revisit that font choice.

**Comment by sebastianbenz** [comment]
@pbakaus ups - accidentally merged it already.

**Pull request merged**
