### PR TITLE
support adding two docs in same folder for special case `amp-ad` `amp…

### PR DESCRIPTION
**Pull request by zhouyx**
Try to update `amp-ad` and `amp-embed` docs to extension. 
https://github.com/ampproject/amphtml/issues/3271

### CODE REVIEW

**Comment by pbakaus** [comment]
Ugh, your github client secret is hardcoded in there – you should probably change it and remove again. Otherwise it's pretty hard to read the actual change due to the formatting changes – we can change tabs to spaces, but let's do it in another PR.

Could you fix these two issues and report back? Thanks!

**Comment by zhouyx** [comment]
Yes! I put that on for testing. I am working on these.

**Comment by zhouyx** [comment]
fixed

**Comment by zhouyx** [comment]
@pbakaus PTAL

**Comment by zhouyx** [comment]
This has been there for a while, please take a look. Thanks!

**Comment by pbakaus** [comment]
Very sorry about the long delay, was on vacation last week and am out for two conferences this week. I'm merging this to master for now, but you'd do be a great favor to port your PR for the "megamerge" branch (we'll switch to this branch soon).

**Comment by zhouyx** [comment]
Thanks for the merge! I will port PR to the other branch.

**Pull request merged**
