### PR TITLE
Add Kenshoo analytics service documentation

### PR DESCRIPTION
**Pull request by leazus**
✨  Add [Kenshoo](https://kenshoo.com/)  documentation to the supported Analytics Vendors docs.

### CODE REVIEW

**Comment by leazus** [comment]
@calebcordry @torch2424 once this [PR](https://github.com/ampproject/amphtml/pull/21458) is merged, could you please review this PR as well?
Thanks!

**Comment by torch2424** [comment]
cc @sebastianbenz for the merge, I don't have merge access on this repo.

For context, it is a new Analytics vendor for AMP, and simply listing themself on the docs. 👍

**Comment by matthiasrohmer** [comment]
Copied the changes to #1658 to have amp.dev stay in sync.

**Comment by matthiasrohmer** [comment]
@sebastianbenz is there something holding us off from merging this and #1658?

**Comment by sebastianbenz** [comment]
@matthiasrohmer no

@leazus Sorry for the delay!

**Comment by leazus** [comment]
@torch2424 @sebastianbenz and @matthiasrohmer Thanks for taking care of this! :1st_place_medal:

**Pull request merged**
