### PR TITLE
Update amp-social-share.md

### PR DESCRIPTION
**Pull request by gam-phon**

### CODE REVIEW

**Comment by gam-phon** [comment]
I signed it!

**Comment by erwinmombay** [comment]
lgtm, thanks for the contribution @gam-phon !

**Comment by gam-phon** [comment]
Welcome ^_^

**Comment by pbakaus** [comment]
This PR sadly won't work. Everything in the _reference folder is auto-generated an pulled from the https://github.com/ampproject/amphtml repo. Thus, it has to be changed here instead: https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/amp-social-share.md

**Comment by gam-phon** [comment]
@pbakaus I have opened a pull request there. Thanks

**Pull request merged**
