### PR TITLE
WIP: AMP Contributors Summit 2019 Event Page

### PR DESCRIPTION
**Pull request by vishaldodiya**
Reference #2360

### CODE REVIEW

**Comment by vishaldodiya** [comment]
@googlebot I signed it!

**Comment by vishaldodiya** [comment]
@googlebot I signed it!

**Comment by mrjoro** [comment]
Thanks @vishaldodiya!

It looks like a lot of the content is directly copying the AMP Conf content, which is currently more of a recap page (since that conference is over).  We'll want to update this page to have information for people thinking about attending AMPCS 2019.  Take a look at some of the content I mentioned in #2360.

As for the overall structure and correctness of the markup to match the look and feel of amp.dev, I'll leave that to @pbakaus to review. :)

**Comment by mrjoro** [comment]
I saw you removed some of the boilerplate @vishaldodiya; I'd be okay with getting a skeleton in with the right basic structure and then we can iterate on it after that.

@pbakaus can you take a look so we can get this in?

Also /cc @cathibosco and @mattludwig as FYI.  At least in future iterations we'll likely want to add some additional assets.

**Pull request merged**
