### PR TITLE
Fix capitalisation of WordPress

### PR DESCRIPTION
**Pull request by davejamesmiller**

### CODE REVIEW

**Comment by davejamesmiller** [comment]
I signed it!

**Comment by pbakaus** [comment]
Thanks!

**Comment by pbakaus** [comment]
Ah sorry, can you rebase/update so I can merge this?

**Comment by davejamesmiller** [comment]
Done, and I fixed on more instance I found too.

**Comment by pbakaus** [comment]
Great thanks!

**Pull request merged**
