### PR TITLE
update links to new ampbyexample.com domain

### PR DESCRIPTION
**Pull request by sebastianbenz**
- change domain from amp-by-example.appspot.com to ampbyexample.com
- add link to new amp-accordion sample
- add link to new amp-audio sample
- add link to amp-fit-text sample
- add link to image galleries with amp-carousel sample
- link to sample sections

### CODE REVIEW

**Comment by sebastianbenz** [comment]
added more sample links:

- add link to amp-vimeo sample
- add link to amp-vine sample
- add link to amp-soundcloud sample
- add link to amp-dailymotion sample

**Comment by pbakaus** [comment]
Looks good, if you resolve the conflicts, I'll merge.

**Comment by sebastianbenz** [comment]
We can actually abandon this PR. I didn't realise at first that the reference docs are imported from the amphtml repo. I've updated the links already there.

**Comment by pbakaus** [comment]
thanks for the update!

**Pull request closed without merging**
