### PR TITLE
Publish Responsive Design guide with embedded samples!

### PR DESCRIPTION
**Pull request by bpaduch**
Changes include:
- **new** Responsive Design Guide with embedded samples
- a "none" styled callout box - no icon, just gray box - used for a basic aside
- addition of h4 and 5 heading style to docs
- remove padding above headings - already has enough margin

to: @pbakaus 
cc: @sebastianbenz  - thank you!

Preview available at: https://ampproject-custom.firebaseapp.com/docs/guides/responsive_design

### CODE REVIEW

**Comment by pbakaus** [comment]
I think it looks fantastic, but I'm unsure about the IA:

* the title is not actionable
* the content logically belongs in the Style & Layout section

Thoughts?

**Comment by pbakaus** [comment]
I also just realized that there are margin issues in the sidebar now, was that on purpose? There's not enough separation between "Develop" and "Style & Layout", which wasn't the case before your PR.

**Comment by bpaduch** [comment]
Agreed, had my blinders on.  Thanks!  New location under Style & Layout with new title "Create Responsive AMP Pages". Will also fix height issue with h5.

**Comment by pbakaus** [comment]
Awesome! LGTM.

**Pull request merged**
