### PR TITLE
improve playground embed preview

### PR DESCRIPTION
**Pull request by sebastianbenz**
screenshot 2019-03-08 at 00 16 19

### CODE REVIEW

**Comment by pbakaus** [comment]
How do you edit long lines that are under the preview?

**Comment by matthiasrohmer** [comment]
Longos suggestion would be to wrap the text on the preview's border.

**Comment by pbakaus** [comment]
@matthiasrohmer I mean that works, but then it's essentially not "inline", and only looks that way, and could equally well be on the side.. you know what I mean? ;)

**Comment by sebastianbenz** [comment]
My thinking was that the boilerplate works in our favour here. It's so long, that you can easily scroll to any other line (we could even ensure this by adding more padding-right to the source code view).

**Comment by sebastianbenz** [comment]
We can’t wrap due to the boilerplate as would spread over multiple lines.

**Comment by sebastianbenz** [comment]
I'll merge for now, but I agree - we need to find a better solution.

**Pull request merged**
