### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by adamzr**
I fixed some grammar mistakes and tried to clarify the language.

### CODE REVIEW

**Comment by adamzr** [comment]
I signed it!

**Comment by pbakaus** [comment]
This looks great, thanks! Could you resolve the conflicts first? I'll merge afterwards.

**Comment by adamzr** [comment]
I signed it!

**Comment by aricheimer** [comment]
Approved!

**Comment by aricheimer** [comment]
I signed it!

**Comment by adamzr** [comment]
@aricheimer @googlebot I committed it under a different email. But, now all authors have approved and signed CLA.

**Comment by adamzr** [comment]
@googlebot I did author those commits.

**Comment by adamzr** [comment]
@pbakaus I merged in the changes. My battle with @googlebot was less successful as you can see :smile: Can you fix that?

**Comment by pbakaus** [comment]
We'll ignore the crazy bot this time, thanks for your contribution!

**Pull request merged**
